# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Web Automation Workflow

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-automation-test:
    runs-on: ubuntu-latest
    
    steps:
    #download repository
    - uses: actions/checkout@v4

    #setup java
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin' #atau oracle

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    # Setup Gradle & Build with Gradle Wrapper tidak dipakai karena yang mau dilakukan adalah menjalankan test
    #- name: Setup Gradle
    #  uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    #- name: Build with Gradle Wrapper
    #  run: ./gradlew build

    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build


    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v2.1.2

    # setup gradle wrapper
    - name: Setup gradlew
      run: chmod +x gradlew

    # execute gradle command for running the cucumber test
    - name: Execute Cucumber Test
      run: ./gradlew cucumber

    # archive test results
    - name: Archive Test Result
      uses: actions/upload-artifact@v7.0.1
      if: always()
      with:
          name: Cucumber Report# optional, default is artifact
          path: reports

    # deploy to GitHub Pages
    - name: Deploy Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4.1.0
      with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: reports
